/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAnchor: typeof import('nocturne-ui/es')['NAnchor']
    NAnchorItem: typeof import('nocturne-ui/es')['NAnchorItem']
    NButton: typeof import('nocturne-ui/es')['NButton']
    NCollapseTransition: typeof import('nocturne-ui/es')['NCollapseTransition']
    NColorPicker: typeof import('nocturne-ui/es')['NColorPicker']
    NDrawer: typeof import('nocturne-ui/es')['NDrawer']
    NIcon: typeof import('nocturne-ui/es')['NIcon']
    NOverlay: typeof import('nocturne-ui/es')['NOverlay']
    NSwitch: typeof import('nocturne-ui/es')['NSwitch']
    NTooltip: typeof import('nocturne-ui/es')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpApiAside: typeof import('./.vitepress/theme/components/vp-api-aside.vue')['default']
    VpApiAsideItem: typeof import('./.vitepress/theme/components/vp-api-aside-item.vue')['default']
    VpApiTyping: typeof import('./.vitepress/theme/components/vp-api-typing.vue')['default']
    VpApp: typeof import('./.vitepress/theme/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/theme/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/theme/components/vp-demo.vue')['default']
    VpDocContent: typeof import('./.vitepress/theme/components/vp-doc-content.vue')['default']
    VpDocSearch: typeof import('./.vitepress/theme/components/vp-doc-search.vue')['default']
    VpHome: typeof import('./.vitepress/theme/components/vp-home.vue')['default']
    VpLastUpdate: typeof import('./.vitepress/theme/components/vp-last-update.vue')['default']
    VpNav: typeof import('./.vitepress/theme/components/vp-nav.vue')['default']
    VpNavMenu: typeof import('./.vitepress/theme/components/vp-nav-menu.vue')['default']
    VpNotFound: typeof import('./.vitepress/theme/components/common/vp-not-found.vue')['default']
    VpPageSwitch: typeof import('./.vitepress/theme/components/vp-page-switch.vue')['default']
    VpSidebar: typeof import('./.vitepress/theme/components/vp-sidebar.vue')['default']
    VpSidebarItem: typeof import('./.vitepress/theme/components/vp-sidebar-item.vue')['default']
    VpThemeToggle: typeof import('./.vitepress/theme/components/common/vp-theme-toggle.vue')['default']
  }
}
