name: Publish to npm registry

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.com/
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Gen npmrc
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> ./.npmrc

      - name: Update npm
        run: npm install npm@9 -g

      - name: Build build-utils
        run: |
          cd internal/build-utils
          pnpm build

      - name: Build&publish
        run: sh ./scripts/publish.sh
        env:
          TAG_VERSION: ${{env.TAG_VERSION}}
          GIT_HEAD: ${{env.GIT_HEAD}}
          NODE_OPTIONS: --max-old-space-size=4096
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          REGISTRY: https://registry.npmjs.com/
